definitions:
  request.Register:
    properties:
      email:
        example: tungstenkitty@gmail.com
        type: string
      password:
        example: Password1@
        maxLength: 72
        minLength: 8
        type: string
      username:
        example: tungsten_kitty
        type: string
    required:
    - email
    - password
    - username
    type: object
  response.ErrorResponse:
    properties:
      error:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: Register an account
      parameters:
      - description: New account data
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/request.Register'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Register an account
      tags:
      - Auth
swagger: "2.0"
