definitions:
  request.Login:
    properties:
      password:
        example: Password1@
        type: string
      username:
        example: tungsten_kitty
        type: string
    required:
    - password
    - username
    type: object
  request.Register:
    properties:
      email:
        example: tungstenkitty@gmail.com
        type: string
      password:
        example: Password1@
        maxLength: 72
        minLength: 8
        type: string
      username:
        example: tungsten_kitty
        type: string
    required:
    - email
    - password
    - username
    type: object
  response.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  response.LoginResponse:
    properties:
      accessToken:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Logging in an account without sso
      parameters:
      - description: New account data
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/request.Login'
      produces:
      - application/json
      responses:
        "200":
          description: Access token
          headers:
            Cookie:
              description: refreshToken=abcd1234; HttpOnly; Path=/api/v1/auth/refresh
              type: string
          schema:
            $ref: '#/definitions/response.LoginResponse'
        "400":
          description: Missing field
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "401":
          description: Wrong credential
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "403":
          description: SSO enabled account
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Login
      tags:
      - Auth
  /api/v1/auth/logout:
    post:
      description: Invalidate the current session
      parameters:
      - description: refreshToken=\<Refresh token here\>
        in: header
        name: Cookie
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          headers:
            Cookie:
              description: refreshToken=; HttpOnly; Path=/api/v1/auth/refresh
              type: string
        "401":
          description: Unknown session
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Logout
      tags:
      - Auth
  /api/v1/auth/refresh:
    post:
      description: Rotate current refresh token
      parameters:
      - description: refreshToken=\<Refresh token here\>
        in: header
        name: Cookie
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          headers:
            Cookie:
              description: refreshToken=abcd1234; HttpOnly; Path=/api/v1/auth/refresh
              type: string
        "401":
          description: Unknown session
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Refresh
      tags:
      - Auth
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: Register an account
      parameters:
      - description: New account data
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/request.Register'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Register an account
      tags:
      - Auth
swagger: "2.0"
